[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
redio_contract = "CFQoHeX28aKhpgsLCSGM2zpou6RkRrwRoHVToWS2B6tQ"

[programs.devnet]
redio_contract = "CFQoHeX28aKhpgsLCSGM2zpou6RkRrwRoHVToWS2B6tQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./creds/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
