name: Anchor Tests

on:
  push:
    branches: [ "**" ]  # @todo: set to main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Solana
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash

      - name: Install Node dependencies
        run: source ~/.bashrc && npm install

      - name: Run Anchor tests
        run: source ~/.bashrc && anchor test --skip-lint   # @todo: remove and resove all of Struct field "*" is unsafe, but is not documented.
